apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend
  namespace: devopsdoor-dev
  labels:
    app: sa-frontend
spec:
  selector:
    matchLabels:
      app: sa-frontend
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-frontend                                  # 6
    spec:
      imagePullSecrets:
      - name: postelicred
      containers:
        - image: harbor.postelic.com/harbor-dev/sa-frontend:1.0.0
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80
